### PR TITLE
Update moment range to v2

### PR DESCRIPTION
**Pull request by moimikey**
# notes
- updates moment-range to use v2 of moment

### CODE REVIEW

**Comment by moimikey** [comment]
@AlanFoster :+1:

**Comment by alistairjcbrown** [comment]
Can we keep changes to a minimum? Any files which don't need to be changed for updating to `v2` should be reverted.

**Comment by moimikey** [comment]
@alistairjcbrown done

**Comment by alistairjcbrown** [comment]
LGTM :+1: 

For the interim, we should use your `update-moment-range-to-v2` branch in our BackOffice `package.json` file so that we remove the `const` error.

Can you open a PR upstream to `onefinestay/react-daterange-picker`?
Probably best to just include the 429203623572ba2088b83c67626251961c8a53ac commit and let them build it, so that the PR diff is nice and small.

**Comment by moimikey** [comment]
@alistairjcbrown awesome :+1: will do.

**Pull request merged**
